### ISSUE TITLE
Importing works, but fails after compiling

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/hxnodejs#50]
1) After installing with `haxelib git hxnodejs git@github.com:HaxeFoundation/hxnodejs.git`;
2) Adding it to the `build.hxml` file:

```
-cp src/haxe
-D js-es5
-lib hxnodejs
-main Main
-js main.js
```

And using the following Main script to test the code:

```haxe
package;

import js.node.http.*;

class Main {

static function main() {
  new Main();
}

public function new() {
    testRest();
  }

  public function testRest() {
    var http = new Client();
    trace(http.request(Method.Get, 'http://www.google.com'));
  }
}
```

After compiling and running it with `node main.js`, I get the following error:

```
$ node main.js                                                                                                                                                                              [2.2.1]
/Users/fullofcaffeine/workspace/code/projectgtd/main.js:100
		var http = new js.node.http.Client();
		               ^
ReferenceError: js is not defined
    at Object.Main.testRest (/Users/fullofcaffeine/workspace/code//main.js:100:18)
    at Object.Main [as __class__] (/Users/fullofcaffeine/workspace//main.js:92:7)
    at Function.Main.main (/Users/fullofcaffeine/workspace/code/main.js:96:2)
    at /Users/fullofcaffeine/workspace/code//main.js:744:6
    at Object.<anonymous> (/Users/fullofcaffeine/workspace/code//main.js:745:3)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
```

The generated javascript: http://pastie.org/private/c8eboqpnrawbxvucolodqa#18

What am I missing?

**Comment by nadako** [comment]
This class is missing a `@:jsRequire` metadata, I'll add it, but note that this kind of usage is deprecated in favor of `js.node.Http.request` method.
